### ISSUE TITLE
Default Sheet Name 'Sheet1' Suggest

### ISSUE THREAD

**Issue by amblerkr** [tgel0/crssnt#4]
It is displayed in different languages of each country. I often forget this. I often think, "Why isn't it working?"

ENG: Sheet1 
Korean: 시트1 

It would be great if you could support in various languages.

&name=movie_manual&mode=manual
I can use this, but I don't use it when it's a single sheet.

**Comment by tgel0** [comment]
Hey @amblerkr,

I added a new commit (https://github.com/tgel0/crssnt/commit/a7b584e6300140de69d178b779d7d10fb40ef67d) which introduces a new way of identifying the default sheet. Instead of looking for the name 'Sheet1' it now looks for the sheet with `id = 0`.

This way it doesn't matter what the name of the sheet is (you could even rename it and it would still work).

You can still use a totally different sheet name with the option `&name=movie_manual`.

Would be great if you could check it out/give feedback 😊

**Comment by amblerkr** [comment]
> Hey @amblerkr,
> 
> I added a new commit ([a7b584e](https://github.com/tgel0/crssnt/commit/a7b584e6300140de69d178b779d7d10fb40ef67d)) which introduces a new way of identifying the default sheet. Instead of looking for the name 'Sheet1' it now looks for the sheet with `id = 0`.
> 
> This way it doesn't matter what the name of the sheet is (you could even rename it and it would still work).
> 
> You can still use a totally different sheet name with the option `&name=movie_manual`.
> 
> Would be great if you could check it out/give feedback 😊

Perfect. Now it works without having to edit '시트1' to 'Sheet 1' or manual feature.

**Comment by amblerkr** [comment]
Perfect. Now it works without having to edit '시트1' to 'Sheet 1' or manual feature.
